$('#voting').click(function(){
    window.location.href='../candidate.html';
 })
 $('#land').click(function(){
    window.location.href='../lr_admin.html';
 })
 $('#citizen').click(function(){
   window.location.href='../citizen_admin.html';
})